class EfdClass:
    codes = dict([
        ("0000","REG,COD_VER,COD_VER,IND_SIT_ESP,IND_SIT_ESP,IND_SIT_ESP,IND_SIT_ESP,NOME,CNPJ,UF,COD_MUN,SUFRAMA,IND_NAT_PJ,IND_ATIV"),
        ("0001","REG,IND_ATIV"),
        ("0100","REG,NOME,CPF,CRC,CNPJ,CEP,END,NUM,COMPL,BAIRRO,FONE,FAX,EMAIL,COD_MUN")
    ])
